# config.yml

# ------------------------
# 경로 설정
# ------------------------
data:
  reference_dir: data/rabbits          # 레퍼런스 이미지 (50장 A-pose 캐릭터)
  test_dir: data/test                  # 테스트 이미지 디렉토리

features:
  embedding_cache: features/embeddings.pth    # 저장될 레퍼런스 임베딩
  generic_bank: features/generic_bank.pth     # GFB 벡터 저장 위치
  patch_file: features/patches.pth            # 모든 이미지 패치 임베딩 (GFB 입력용)
  gfb_option: B                               # A → 평균 기반 / B → K-means 기반 (더 general)

# ------------------------
# 이미지 설정
# ------------------------
image:
  size: [512, 512]     # 모델 입력 해상도
  normalization:
    mean: [0.485, 0.456, 0.406]    # ImageNet mean
    std: [0.229, 0.224, 0.225]     # ImageNet std

# ------------------------
# GFB 필터링 기준
# ------------------------
gfb:
  threshold: 0.9       # generic patch 판단 기준 유사도
  min_count: 10        # (Option A) 특정 패치가 generic 되기 위한 최소 등장 횟수
  cluster_method: kmeans
  n_clusters: 25

# ------------------------
# 시각화 출력
# ------------------------
output_dir: output
